import { PrismaService } from '../../../../dist/src/prisma/prisma.service.js';
import { CreateUserDto } from './dto/create-user.dto.js';
import { UpdateUserDto } from './dto/update-user.dto.js';
export declare class UserService {
    private prisma;
    constructor(prisma: PrismaService);
    create(createUserDto: CreateUserDto): Promise<{
        id: number;
        createdAt: Date;
        email: string;
        password: string;
        phone: string | null;
        name: string;
        age: number;
        bio: string | null;
        weight: number | null;
        height: number | null;
        nationality: string | null;
        gender: import("@prisma/client").$Enums.Gender | null;
        city: string | null;
        country: string | null;
        role: import("@prisma/client").$Enums.Role;
        zodiacSign: string | null;
        seeking: string | null;
        location: string | null;
        job: string | null;
        hobbies: string[];
        spotifyId: string | null;
        musicList: string[];
        subscription: import("@prisma/client").$Enums.SubscriptionTier;
        donationsEnabled: boolean;
        isRestricted: boolean;
        updatedAt: Date;
    }>;
    findByEmail(email: string): Promise<{
        id: number;
        createdAt: Date;
        email: string;
        password: string;
        phone: string | null;
        name: string;
        age: number;
        bio: string | null;
        weight: number | null;
        height: number | null;
        nationality: string | null;
        gender: import("@prisma/client").$Enums.Gender | null;
        city: string | null;
        country: string | null;
        role: import("@prisma/client").$Enums.Role;
        zodiacSign: string | null;
        seeking: string | null;
        location: string | null;
        job: string | null;
        hobbies: string[];
        spotifyId: string | null;
        musicList: string[];
        subscription: import("@prisma/client").$Enums.SubscriptionTier;
        donationsEnabled: boolean;
        isRestricted: boolean;
        updatedAt: Date;
    } | null>;
    findAll(): Promise<({
        photos: {
            id: number;
            createdAt: Date;
            url: string;
            isPrimary: boolean;
            userId: number;
        }[];
    } & {
        id: number;
        createdAt: Date;
        email: string;
        password: string;
        phone: string | null;
        name: string;
        age: number;
        bio: string | null;
        weight: number | null;
        height: number | null;
        nationality: string | null;
        gender: import("@prisma/client").$Enums.Gender | null;
        city: string | null;
        country: string | null;
        role: import("@prisma/client").$Enums.Role;
        zodiacSign: string | null;
        seeking: string | null;
        location: string | null;
        job: string | null;
        hobbies: string[];
        spotifyId: string | null;
        musicList: string[];
        subscription: import("@prisma/client").$Enums.SubscriptionTier;
        donationsEnabled: boolean;
        isRestricted: boolean;
        updatedAt: Date;
    })[]>;
    findOne(id: number): Promise<{
        photos: {
            id: number;
            createdAt: Date;
            url: string;
            isPrimary: boolean;
            userId: number;
        }[];
    } & {
        id: number;
        createdAt: Date;
        email: string;
        password: string;
        phone: string | null;
        name: string;
        age: number;
        bio: string | null;
        weight: number | null;
        height: number | null;
        nationality: string | null;
        gender: import("@prisma/client").$Enums.Gender | null;
        city: string | null;
        country: string | null;
        role: import("@prisma/client").$Enums.Role;
        zodiacSign: string | null;
        seeking: string | null;
        location: string | null;
        job: string | null;
        hobbies: string[];
        spotifyId: string | null;
        musicList: string[];
        subscription: import("@prisma/client").$Enums.SubscriptionTier;
        donationsEnabled: boolean;
        isRestricted: boolean;
        updatedAt: Date;
    }>;
    update(id: number, updateUserDto: UpdateUserDto): Promise<{
        id: number;
        createdAt: Date;
        email: string;
        password: string;
        phone: string | null;
        name: string;
        age: number;
        bio: string | null;
        weight: number | null;
        height: number | null;
        nationality: string | null;
        gender: import("@prisma/client").$Enums.Gender | null;
        city: string | null;
        country: string | null;
        role: import("@prisma/client").$Enums.Role;
        zodiacSign: string | null;
        seeking: string | null;
        location: string | null;
        job: string | null;
        hobbies: string[];
        spotifyId: string | null;
        musicList: string[];
        subscription: import("@prisma/client").$Enums.SubscriptionTier;
        donationsEnabled: boolean;
        isRestricted: boolean;
        updatedAt: Date;
    }>;
    remove(id: number): Promise<{
        id: number;
        createdAt: Date;
        email: string;
        password: string;
        phone: string | null;
        name: string;
        age: number;
        bio: string | null;
        weight: number | null;
        height: number | null;
        nationality: string | null;
        gender: import("@prisma/client").$Enums.Gender | null;
        city: string | null;
        country: string | null;
        role: import("@prisma/client").$Enums.Role;
        zodiacSign: string | null;
        seeking: string | null;
        location: string | null;
        job: string | null;
        hobbies: string[];
        spotifyId: string | null;
        musicList: string[];
        subscription: import("@prisma/client").$Enums.SubscriptionTier;
        donationsEnabled: boolean;
        isRestricted: boolean;
        updatedAt: Date;
    }>;
    findDerived(minAge: number, maxAge: number, country?: string): Promise<({
        photos: {
            id: number;
            createdAt: Date;
            url: string;
            isPrimary: boolean;
            userId: number;
        }[];
    } & {
        id: number;
        createdAt: Date;
        email: string;
        password: string;
        phone: string | null;
        name: string;
        age: number;
        bio: string | null;
        weight: number | null;
        height: number | null;
        nationality: string | null;
        gender: import("@prisma/client").$Enums.Gender | null;
        city: string | null;
        country: string | null;
        role: import("@prisma/client").$Enums.Role;
        zodiacSign: string | null;
        seeking: string | null;
        location: string | null;
        job: string | null;
        hobbies: string[];
        spotifyId: string | null;
        musicList: string[];
        subscription: import("@prisma/client").$Enums.SubscriptionTier;
        donationsEnabled: boolean;
        isRestricted: boolean;
        updatedAt: Date;
    })[]>;
    getStatsByCountry(): Promise<unknown>;
}
